[package]
name = "vm_control"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[features]


[dependencies]
byteorder = "*"
kvm = { path = "../kvm" }
libc = "*"
resources = { path = "../resources" }
sys_util = { path = "../sys_util" }
