[package]
name = "p9"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
libc = "*"
wire_format_derive = { path = "wire_format_derive" }
sys_util = { path = "../sys_util" }

[features]
trace = []
