[package]
name = "devices"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
bit_field = { path = "../bit_field" }
byteorder = "*"
data_model = { path = "../data_model" }
enumn = { path = "../enumn" }
kvm = { path = "../kvm" }
libc = "*"
net_sys = { path = "../net_sys" }
net_util = { path = "../net_util" }
remain = "*"
resources = { path = "../resources" }
sync = { path = "../sync" }
sys_util = { path = "../sys_util" }
virtio_sys = { path = "../virtio_sys" }
vm_control = { path = "../vm_control" }
